services:
    geodis.rest_api:
        class: Geodis\Manager\GeodisJsonApi
        arguments: ['@doctrine.orm.entity_manager']

    geodis.exceptionlistener:
        class: aibianchi\ExactOnlineBundle\Event\ExceptionListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: monolog.logger, channel: exactAPI }
